### ISSUE TITLE
Can't be used with @formkit v1.0.0-beta.9

### ISSUE THREAD

**Issue by alvaro-canepa** [kgierke/formkit-inputs#11]
After upgrade to beta-9 I can't start the application. 
![image](https://user-images.githubusercontent.com/5142298/178099258-30155ea1-9d09-4c6d-b2f0-31c529e92d51.png)

### Breaking changes
> Composables from @formkit/inputs have been replaced with "sections". This should only affect users who were creating their own inputs from pre-existing composables.

Composable `useSchema` require a function as first param.  
Can you fix it or tell how to do that and I can make a PR?. 

Thanks

**Comment by kgierke** [comment]
Hi, thanks for the report, I'll gonna have a look at it tomorrow morning.

**Comment by kgierke** [comment]
This issue should be fixed with version 0.3.3. Please be aware depending on the version you used before, that I changed the single image input behaviour to only return a string as value instead of an object.

**Comment by alvaro-canepa** [comment]
Great @kgierke many thanks, I will update!
