### ISSUE TITLE
Package distribution improvements

### ISSUE THREAD

**Issue by justin-schroeder** [kgierke/formkit-inputs#5]
Wanted to give this a try on a project using laravel mix and was unable to run it:

![image](https://user-images.githubusercontent.com/1950463/158262381-ae47aaf3-2cbf-48c2-8c08-10245b4adcde.png)

Bunding for package distribution can be a pain. Here are a few things that might help:

1. An export map in packages.json:

```JSON
{
  ...
  "exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.cjs",
      "types": "./dist/index.d.ts"
    }
  }
}
```

2. A `module` key in your package.json, like:

```
  "module": "dist/index.mjs",
```

3. Rollup into a single `.mjs` and a `.cjs` file. You can use [rollup](https://rollupjs.org/guide/en/) for this (admittedly a pain).

**Comment by kgierke** [comment]
Thanks for the info, yeah had a quick look into this in the beginning and wanted to postpone this. But apparently it can't wait any longer. Will try to fix this by tomorrow.

**Comment by kgierke** [comment]
Added Rollup to support this, it should now work as expected.
